### ISSUE TITLE
Pretrained model weights for shapeNet

### ISSUE THREAD

**Issue by ksos104** [Liuxinyv/SAZS#5]
Can you provide the pretrained model weights for shapeNet? When I try to train the model, the error occurs that there is no file named './checkpoints/distance_measure_regressor.pth'

**Comment by Ako-r** [comment]
Maybe you can refer to https://github.com/Qualcomm-AI-research/InverseForm/releases/download/v1.0/distance_measures_regressor.pth. But I am not sure.
